[profile.default]
solc_version = "0.8.24"
src = 'src'
out = 'out'
libs = ['lib']
evm_version = 'paris'

[fmt]
bracket_spacing = true
line_length = 140
multiline_func_header = "all"
number_underscore="thousands"

[doc]
title = "Rhinestone Registry"
ignore = ["src/DataTypes.sol", "src/Common.sol", "src/external"]

[invariant]
# fail_on_revert = true
runs = 1200
depth = 20
