[profile.default]
solc_version = "0.8.24"
src = 'src'
out = 'out'
libs = ['lib']
evm_version = 'paris'

[fmt]
bracket_spacing = true
line_length = 100
multiline_func_header = "all"
number_underscore="thousands"

[invariant]
# fail_on_revert = true
runs = 1200
depth = 20
